---

domain: pcf-services.com

disable_local_firewall: true

# Root keys
root:
  password: ej343fa8f4038e4f

services:

  aws:
    # AWS credentials passed along to chef cookbooks via an encrypted data bag
    aws_automation_key: "<<AWS_AUTOMATION_ACCESS_KEY_ID$AWS Access Key ID: "
    aws_automation_secret: "<<AWS_AUTOMATION_SECRET_ACCESS_KEY*AWS Secret Access Key: "

  vsphere:
    vsphere_host: "<<VSPHERE_HOST$VSphere host: "
    vsphere_dc: "<<VSPHERE_DC$VSphere data center: "
    vsphere_user: "<<VSPHERE_USER$VSphere automation user name: "
    vsphere_pass: "<<VSPHERE_PASS*VSphere automation user password: "
    ssh_key_file: pivotal-tech

ntp:
  sync_clock: true
  servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

database:
  backup_password: 0p3n5tack
  replication_password: 0p3n5tack
  port: 3306

messaging:
  user: openstack
  password: 0p3n5tack
  cookie: c69bba0d4a8fa5ca6db11bd44acb8fda
  use_ssl: true
  ampq_port: &ampq_port 5671
  ampq_mgmt_port: &ampq_mgmt_port 15671
  services_path: os_services
  compute_path: os_compute_kvm
  use_openstack_ha: true

# Load balancing proxy
proxy:

  fqdn: &proxy_fqdn os.pcf-services.com
  vip_address: &frontend_vip_address 10.103.43.25
  vip_cidr_netmask: 23
  vip_nic: eth1

  frontend_fqdn: *proxy_fqdn
  backend_fqdn: *proxy_fqdn

  server_pools:
    db:
      pool_cluster_name: database
      profile: mysql
    #mq:
    #  pool_cluster_name: messaging
    #  port: *ampq_port
    #  profile: rabbitmq
    mq_admin:
      pool_cluster_name: messaging
      port: *ampq_mgmt_port
      profile: ssl
    identity-api:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    identity-admin:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    image-api:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    block-storage-api:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    compute-api:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    compute-ec2-api:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    compute-novnc:
      pool_cluster_name: services
      profile: tcp
    network-api:
      pool_cluster_name: services
      profile: http
      bind_ssl: app_proxy
    horizon_web:
      pool_cluster_name: services
      port: 80
      profile: http
    horizon_web_ssl:
      pool_cluster_name: services
      port: 443
      profile: ssl

openstack:
  region: durham

  passwords:
    admin_password: 0p3n5tack
    service_password: 0p3n5tack
    service_token: 0c4a1365e0bbb7e2e02543a2b932cfed
    metadata_token: ad1fb85ef72a61e91c23418b4bf908ce
    # Password to use for openstack database users
    database_password: 0p3n5tack

  # OpenStack endpoints
  endpoints:

    # Proxy end-point for OpenStack app services
    openstack_app_proxy: *proxy_fqdn
    # Proxy end-point for OpenStack ops services
    openstack_ops_proxy: *proxy_fqdn

    # Use SSL for all end-points
    use_ssl: true
    is_insecure: true

    identity-api:
      port: 5000
    identity-admin:
      port: 35357
    image-api:
      port: 9292
    block-storage-api:
      port: 8776
    compute-api:
      port: 8774
    compute-ec2-api:
      port: 8773
    compute-novnc:
      port: 6080
    network-api:
      port: 9696

  image:
    #notifier_strategy: 'rabbit'
    notifier_strategy: noop
    #notification_driver: 'messaging'
    notification_driver: noop

  compute:
    rate_limits:
      generic-post-limit: 500
      create-servers-limit: 500
      generic-put-limit: 500
      changes-since-limit: 500
      generic-delete-limit: 500

  # OpenStack Neutron settings
  network:
    ml2:
      type_drivers: flat,vlan,vxlan
      tenant_network_types: vlan,vxlan
      tunnel_types: vxlan
      mechanism_drivers: openvswitch
    ovs:
      physical_network_tag: physnet
      vlan_ranges: 1:4094
      # Applied only if using VXLAN tunnels
      vni_ranges: 1:10000
      vxlan_group: 239.1.1.1
      # Applied only if using GRE tunnels
      tunnel_id_ranges: 1:10000
      # OVS specific configuration
      external_bridge: br-eth1
      external_interface: eth1

# log configuration
logs:
  type: syslog
  logio:
    ports:
      http: 9081
      stream: 28777
  syslog:
    haproxy:
      protocol: tcp
      port: 51400
  loggers:
    horizon:
      level: DEBUG
    keystone:
      level: DEBUG
    glance:
      level: DEBUG
    cinder:
      level: DEBUG
    neutron:
      level: DEBUG
    nova:
      level: DEBUG

vsphere:

  public_vlan: VM Network
  public_vlan_gateway: 10.103.42.1
  public_vlan_dns: 10.103.42.135
  public_vlan_dns_suffixes: fe.gopivotal.com
  public_ips: 10.103.43.5:20/23

  private_vlan: Data Network

  vm_folder: OpenStack
  vm_datastore: datastore36
